"""updated policy data schema

Revision ID: 0afc4b47e575
Revises: 
Create Date: 2026-04-30 11:46:21.726394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afc4b47e575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. પહેલા જૂનું ટેબલ ડ્રોપ કરો (જો ડેટા મહત્વનો ન હોય તો)
    op.drop_table('policy_data')
    
    # 2. નવું ટેબલ બનાવો જે તમારા નવા ક્લાસ મુજબ હોય
    op.create_table('policy_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('age', sa.String(length=10), nullable=True),
        sa.Column('policy_type', sa.String(length=100), nullable=True),
        sa.Column('premium', sa.String(length=50), nullable=True),
        sa.Column('benefit_amount', sa.String(length=100), nullable=True),
        sa.Column('elimination_period', sa.String(length=100), nullable=True),
        sa.Column('inflation_protection', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_data_session_id'), 'policy_data', ['session_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_data', 'created_at')
    op.drop_column('policy_data', 'is_active')
    op.drop_column('policy_data', 'version')
    op.drop_column('policy_data', 'id')
    # ### end Alembic commands ###
